# Generated by Django 5.1.7 on 2025-03-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_video_alter_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
